repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.40.0
    hooks:
      - id: ggshield
        name: GitGuardian Shield
        entry: ggshield secret scan pre-commit
        language: python
        stages: [pre-commit]
        types: [text]

  - repo: local
    hooks:
      - id: pytest
        name: Run tests with coverage
        entry: python -B -m pytest -c pytest-precommit.ini -p no:cacheprovider
        language: python
        pass_filenames: false
        always_run: true
        files: '^(src/|tests/)'
        types: [python]
        additional_dependencies: [pytest>=8.0.0, pytest-cov>=6.0.0, click>=8.0.0]
