name: Auto-Fix CI Failures

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  notify-claude:
    name: Notify Claude GitHub Agent
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && (github.event.workflow_run.event == 'pull_request' || github.event.workflow_run.event == 'workflow_dispatch') }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get PR number from workflow run
      id: get-pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RUN_ID="${{ github.event.workflow_run.id }}"

        # Get PR number directly from the workflow run object
        PR_NUMBER=$(gh api /repos/${{ github.repository }}/actions/runs/$RUN_ID --jq '.pull_requests[0].number // empty')

        # Validate we got a valid PR number
        if [ -z "$PR_NUMBER" ]; then
          echo "Error: Could not find PR for workflow run $RUN_ID"
          exit 1
        fi

        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "Found PR #$PR_NUMBER"

    - name: Invoke Claude to fix CI failure
      uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        prompt: |
          The CI workflow failed for PR #${{ steps.get-pr.outputs.pr_number }}.

          Workflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}

          Please:
          1. Check the failed workflow logs
          2. Identify the root cause
          3. Fix the issue
          4. Push the fixes to this PR
