name: Auto-Fix CI Failures

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  notify-claude:
    name: Notify Claude GitHub Agent
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && (github.event.workflow_run.event == 'pull_request' || github.event.workflow_run.event == 'workflow_dispatch') }}

    steps:
    - name: Get PR number from workflow run
      id: get-pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RUN_ID="${{ github.event.workflow_run.id }}"
        HEAD_BRANCH="${{ github.event.workflow_run.head_branch }}"

        # Try to get PR number from API first (works for pull_request events)
        PR_NUMBER=$(gh api /repos/${{ github.repository }}/actions/runs/$RUN_ID/pull_requests --jq '.[0].number' 2>/dev/null || echo "")

        # If that fails, look up PR by branch name (works for workflow_dispatch)
        if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
          PR_NUMBER=$(gh pr list --head "$HEAD_BRANCH" --state open --json number --jq '.[0].number // empty')
        fi

        # Validate we got a valid PR number
        if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
          echo "Error: Could not find PR for branch $HEAD_BRANCH"
          exit 1
        fi

        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "Found PR #$PR_NUMBER for branch $HEAD_BRANCH"

    - name: Post Claude GitHub Agent comment
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER="${{ steps.get-pr.outputs.pr_number }}"
        RUN_ID="${{ github.event.workflow_run.id }}"

        gh pr comment $PR_NUMBER --body "$(cat <<'EOF'
        @claude The CI workflow failed for this PR.

        **Workflow Run:** https://github.com/${{ github.repository }}/actions/runs/$RUN_ID

        Please:
        1. Check the failed workflow logs
        2. Identify the root cause
        3. Fix the issue
        4. Push the fixes to this PR
        EOF
        )"
