name: Auto-Fix CI Failures

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  notify-claude:
    name: Notify Claude GitHub Agent
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request' }}

    steps:
    - name: Get PR number from workflow run
      id: get-pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RUN_ID="${{ github.event.workflow_run.id }}"

        # Get PR numbers from the workflow run
        PR_NUMBER=$(gh api /repos/${{ github.repository }}/actions/runs/$RUN_ID/pull_requests --jq '.[0].number')
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "Found PR #$PR_NUMBER"

    - name: Post Claude GitHub Agent comment
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER="${{ steps.get-pr.outputs.pr_number }}"
        RUN_ID="${{ github.event.workflow_run.id }}"

        gh pr comment $PR_NUMBER --body "$(cat <<'EOF'
        @claude The CI workflow failed for this PR.

        **Workflow Run:** https://github.com/${{ github.repository }}/actions/runs/$RUN_ID

        Please:
        1. Check the failed workflow logs
        2. Identify the root cause
        3. Fix the issue
        4. Push the fixes to this PR
        EOF
        )"
