name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files

  build:
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
    - uses: actions/checkout@v4

    - name: Run basic checks
      run: |
        echo "Running CI pipeline..."
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"

    - name: List files
      run: |
        echo "Files in repository:"
        find . -type f -not -path './.git/*' | head -20
