name: Claude Code Action

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-code:
    name: Claude Code Assistant
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prepare PATH
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$(go env GOPATH 2>/dev/null || echo $HOME/go)/bin" >> $GITHUB_PATH

    - name: Claude Code Action Official
      uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        github_token: ${{ secrets.AUTO_FIX_PAT }}
        trigger_phrase: "@claude"
        claude_args: |
          --allowedTools "Read,Glob,Grep,Edit,Write,MultiEdit,WebFetch,WebSearch,Bash(*)"
          --max-turns 50
